version: '3.7'

services:
  main:
    container_name: automobile-management
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:dev

    networks:
      - webnet

networks:
  webnet:
volumes:
  pgdata:
